name: 'Action File-Generator'
description: 'Copy paste file according to a filespecification'
branding:
  icon: activity
  color: green
inputs:
  folder:
    description: The folder path to start at
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
